#ifndef POLYMER_PROTOCOL_H_
#define POLYMER_PROTOCOL_H_

namespace polymer {

enum class StatusProtocol { Response, Pong, Count };

enum class LoginProtocol { Disconnect, EncryptionRequest, LoginSuccess, SetCompression, LoginPluginRequest, Count };

enum class PlayProtocol {
  SpawnEntity,
  SpawnExperienceOrb,
  SpawnPlayer,
  EntityAnimation,
  AwardStatistics,
  AcknowledgeBlockChange,
  SetBlockDestroyStage,
  BlockEntityData,
  BlockAction,
  BlockUpdate,
  BossBar,
  ServerDifficulty,
  ClearTitles,
  CommandSuggestionsResponse,
  Commands,
  CloseContainer,
  SetContainerContent,
  SetContainerProperty,
  SetContainerSlot,
  SetCooldown,
  ChatSuggestions,
  PluginMessage,
  DeleteMessage,
  Disconnect,
  DisguisedChatMessage,
  EntityEvent,
  Explosion,
  UnloadChunk,
  GameEvent,
  OpenHorseScreen,
  InitializeWorldBorder,
  KeepAlive,
  ChunkData,
  WorldEvent,
  Particle,
  UpdateLight,
  Login,
  MapData,
  MerchantOffers,
  EntityPosition,
  EntityPositionAndRotation,
  EntityRotation,
  VehicleMove,
  OpenBook,
  OpenScreen,
  OpenSignEditor,
  Ping,
  PlaceGhostRecipe,
  PlayerAbilities,
  PlayerChatMessage,
  EndCombatEvent,
  EnterCombatEvent,
  DeathCombatEvent,
  PlayerInfoRemove,
  PlayerInfoUpdate,
  LookAt,
  PlayerPositionAndLook,
  UpdateRecipeBook,
  RemoveEntities,
  RemoveEntityEffect,
  ResourcePackSend,
  Respawn,
  SetHeadRotation,
  UpdateSectionBlocks,
  SelectAdvancementTab,
  ServerData,
  SetActionBarText,
  WorldBorderCenter,
  WorldBorderLerpSize,
  WorldBorderSize,
  WorldBorderWarningDelay,
  WorldBorderWarningDistance,
  Camera,
  SetHeldItem,
  SetCenterChunk,
  SetRenderDistance,
  SetDefaultSpawnPosition,
  DisplayObjective,
  EntityMetadata,
  LinkEntities,
  EntityVelocity,
  EntityEquipment,
  SetExperience,
  UpdateHealth,
  UpdateObjectives,
  SetPassengers,
  Teams,
  UpdateScore,
  UpdateSimulationDistance,
  SetSubtitleText,
  TimeUpdate,
  SetTitleText,
  SetTitleAnimationTimes,
  EntitySoundEffect,
  SoundEffect,
  StopSound,
  SystemChatMessage,
  PlayerListHeaderAndFooter,
  NBTQueryResponse,
  CollectItem,
  EntityTeleport,
  UpdateAdvancements,
  UpdateAttributes,
  FeatureFlags,
  EntityEffect,
  UpdateRecipes,
  Tags,

  Count
};

} // namespace polymer

#endif
